import os
import sys
from dotenv import load_dotenv
from encrypt import decrypt_value, ENCRYPTION_KEY


load_dotenv()

# Apply admin-UI model overrides (data/model_overrides.json) to os.environ
# BEFORE reading any model-related env vars. Non-empty overrides act as a
# .env-equivalent source. See model_overrides.py for the mapping.
try:
    from model_overrides import apply_overrides_to_env
    apply_overrides_to_env()
except Exception:
    pass  # Overrides are optional; a failure here must not block startup.

# Optional bundled credentials module (generated by scripts/generate_build_config.py
# and included in PyInstaller client builds). Gitignored, not present in dev.
try:
    import _build_config as _bc
except ImportError:
    _bc = None


def _env_or_build(name, default=''):
    """Resolve a credential per-variable:
    1. os.getenv(name) wins if set to a non-empty value (.env override)
    2. _build_config.<name> supplies the value otherwise (bundled default)
    3. `default` as last resort
    Only used for the allow-listed credential values — NOT for operational
    config like HOST_PORT, LOG_LEVEL, WINTASK_*, etc.
    """
    v = os.getenv(name)
    if v:
        return v
    if _bc is not None:
        v = getattr(_bc, name, None)
        if v:
            return v
    return default

# =============================================================================
# Secure Credential Loading
# =============================================================================
# Populates os.environ with API_KEY (from Windows Registry) and sensitive
# credentials (from encrypted LocalSecretsManager) BEFORE anything else reads
# config values.  All existing os.getenv() calls work unchanged.
# Priority: Registry/Secrets > .env > missing
# =============================================================================

# Ensure the install root is on sys.path so PyInstaller-bundled exes
# can find secure_config.py and local_secrets.py at C:\Program Files\AIHub\
_app_root = os.getenv('APP_ROOT', '')
if _app_root and _app_root not in sys.path:
    sys.path.insert(0, _app_root)

try:
    from secure_config import load_secure_config
    load_secure_config()
except ImportError:
    pass  # secure_config not available (dev environment or not yet deployed)

# App's master password - embedded in the executable
encryption_key = ENCRYPTION_KEY

# Application root - used as base for all relative paths
_APP_ROOT = os.path.abspath(os.getenv('APP_ROOT', os.path.dirname(os.path.abspath(__file__))))

# Folders
APP_VERSION = "1.6"  # Deprecated
APP_TEMP_FOLDER = os.path.join(_APP_ROOT, 'temp')
APP_UPLOADS_FOLDER = 'uploads'
LOG_LEVEL = os.getenv('LOG_LEVEL')
ENABLE_SQL_LOG = True

# Resolve all log paths to absolute using APP_ROOT so services in
# subdirectories (PyInstaller one-dir builds) always write to the
# central logs/ folder.
def _resolve_log_path(env_var, default_filename):
    """Return an absolute log path.  Uses the env-var value when set,
    otherwise falls back to ``<APP_ROOT>/logs/<default_filename>``."""
    raw = os.getenv(env_var)
    if raw:
        return os.path.join(_APP_ROOT, raw) if not os.path.isabs(raw) else raw
    return os.path.join(_APP_ROOT, 'logs', default_filename)

LOG_DIR            = _resolve_log_path('LOG_DIR',            'app_log.txt')
LOG_DIR_DATA       = _resolve_log_path('LOG_DIR_DATA',       'data_log.txt')
LOG_DIR_AGENT      = _resolve_log_path('LOG_DIR_AGENT',      'agent_log.txt')
DOC_JOB_QUEUE_LOG  = _resolve_log_path('DOC_JOB_QUEUE_LOG',  'document_job_queue_processor.txt')
DOC_VECTOR_API_LOG = _resolve_log_path('DOC_VECTOR_API_LOG',  'doc_vector_api_log.txt')
ENV_BUNDLE_PATH = os.path.join(_APP_ROOT, 'agent_environments', 'python-bundle')

# System Database Server
DATABASE_SERVER = _env_or_build('DATABASE_SERVER', 'localhost')
DATABASE_NAME = _env_or_build('DATABASE_NAME', 'AIHUB')
DATABASE_UID = _env_or_build('DATABASE_UID', '')
DATABASE_PWD = _env_or_build('DATABASE_PWD', '')

# Cloud Database Server
CLOUD_DATABASE_SERVER = _env_or_build('CLOUD_DATABASE_SERVER', DATABASE_SERVER)
CLOUD_DATABASE_NAME = _env_or_build('CLOUD_DATABASE_NAME', DATABASE_NAME)
CLOUD_DATABASE_UID = _env_or_build('CLOUD_DATABASE_UID', DATABASE_UID)
CLOUD_DATABASE_PWD = _env_or_build('CLOUD_DATABASE_PWD', DATABASE_PWD)

# Azure OpenAI
AZURE_OPENAI_BASE_URL = _env_or_build('AZURE_OPENAI_BASE_URL', '')
AZURE_OPENAI_API_KEY_ENCRYPTED = _env_or_build('AZURE_OPENAI_API_KEY_ENCRYPTED', '')
AZURE_OPENAI_API_KEY = decrypt_value(AZURE_OPENAI_API_KEY_ENCRYPTED, encryption_key) if AZURE_OPENAI_API_KEY_ENCRYPTED else os.getenv('AZURE_OPENAI_API_KEY', '')
AZURE_OPENAI_DEPLOYMENT_NAME = os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME', 'gpt-5.2')
AZURE_OPENAI_DEPLOYMENT_NAME_EMBEDDING = os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME_EMBEDDING', 'text-embedding-3-small')
AZURE_OPENAI_API_VERSION = os.getenv('AZURE_OPENAI_API_VERSION', '2024-12-01-preview')

AZURE_OPENAI_BASE_URL_ALTERNATE = _env_or_build('AZURE_OPENAI_BASE_URL_ALTERNATE', AZURE_OPENAI_BASE_URL)
AZURE_OPENAI_API_KEY_ALTERNATE_ENCRYPTED = _env_or_build('AZURE_OPENAI_API_KEY_ALTERNATE_ENCRYPTED', '')
AZURE_OPENAI_API_KEY_ALTERNATE = decrypt_value(AZURE_OPENAI_API_KEY_ALTERNATE_ENCRYPTED, encryption_key) if AZURE_OPENAI_API_KEY_ALTERNATE_ENCRYPTED else os.getenv('AZURE_OPENAI_API_KEY_ALTERNATE', AZURE_OPENAI_API_KEY)
AZURE_OPENAI_DEPLOYMENT_NAME_ALTERNATE = os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME_ALTERNATE', AZURE_OPENAI_DEPLOYMENT_NAME)
AZURE_OPENAI_DEPLOYMENT_NAME_ALTERNATE_MINI = os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME_ALTERNATE_MINI', 'gpt-5.4-mini')
AZURE_OPENAI_API_VERSION_ALTERNATE = os.getenv('AZURE_OPENAI_API_VERSION_ALTERNATE', AZURE_OPENAI_API_VERSION)

AZURE_OPENAI_BASE_URL_MINI = _env_or_build('AZURE_OPENAI_BASE_URL_MINI', AZURE_OPENAI_BASE_URL)
AZURE_OPENAI_API_KEY_ENCRYPTED_MINI = _env_or_build('AZURE_OPENAI_API_KEY_ENCRYPTED_MINI', '')
AZURE_OPENAI_API_KEY_MINI = decrypt_value(AZURE_OPENAI_API_KEY_ENCRYPTED_MINI, encryption_key) if AZURE_OPENAI_API_KEY_ENCRYPTED_MINI else os.getenv('AZURE_OPENAI_API_KEY_MINI', AZURE_OPENAI_API_KEY)
AZURE_OPENAI_DEPLOYMENT_NAME_MINI = os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME_MINI', 'gpt-5.4-mini')
AZURE_OPENAI_API_VERSION_MINI = os.getenv('AZURE_OPENAI_API_VERSION_MINI', AZURE_OPENAI_API_VERSION)

# OpenAI
USE_OPENAI_API = False   # Use Azure API for non-BYOK; BYOK users still get direct OpenAI via Priority 1
OPENAI_API_BASE_URL = "https://api.openai.com/v1"
OPENAI_API_KEY_ENCRYPTED = _env_or_build('OPENAI_API_KEY_ENCRYPTED', '')
OPENAI_API_KEY = decrypt_value(OPENAI_API_KEY_ENCRYPTED, encryption_key) if OPENAI_API_KEY_ENCRYPTED else os.getenv('OPENAI_API_KEY', '')
OPENAI_DEPLOYMENT_NAME = os.getenv('OPENAI_MODEL', 'gpt-5.2')
OPENAI_DEPLOYMENT_NAME_MINI = os.getenv('OPENAI_MODEL_MINI', 'gpt-5.4-mini')
# Vision model used by command_center_service upload fallback (only fires when
# Claude Vision fails AND BYOK direct OpenAI is active). Preserves the previous
# 'gpt-4o' literal that was hardcoded in upload.py.
OPENAI_VISION_MODEL = os.getenv('OPENAI_VISION_MODEL', 'gpt-4o')

# Anthropic
ANTHROPIC_MODEL = os.getenv('ANTHROPIC_MODEL')
ANTHROPIC_MAX_TOKENS = os.getenv('ANTHROPIC_MAX_TOKENS')
ANTHROPIC_API_KEY_ENCRYPTED = _env_or_build('ANTHROPIC_API_KEY_ENCRYPTED', '')
ANTHROPIC_API_KEY = decrypt_value(ANTHROPIC_API_KEY_ENCRYPTED, encryption_key) if ANTHROPIC_API_KEY_ENCRYPTED else os.getenv('ANTHROPIC_API_KEY', '')
ANTHROPIC_API_THROTTLE_CALLS = os.getenv('ANTHROPIC_API_THROTTLE_CALLS', 'false').lower() in ['true', '1', 't', 'y', 'yes']
ANTHROPIC_API_THROTTLE_DELAY = os.getenv('ANTHROPIC_API_THROTTLE_DELAY')
ANTHROPIC_ADVANCED = os.getenv('ANTHROPIC_ADVANCED', 'claude-opus-4-6')
ANTHROPIC_MINI = os.getenv('ANTHROPIC_MINI', 'claude-sonnet-4-6')

# NLQ (Natural Language Query) LLM Provider: "openai" or "anthropic"
NLQ_PROVIDER = os.getenv('NLQ_PROVIDER', 'anthropic')

# Misc Keys
TAVILY_API_KEY_ENCRYPTED = _env_or_build('TAVILY_API_KEY_ENCRYPTED', '')
TAVILY_API_KEY = decrypt_value(TAVILY_API_KEY_ENCRYPTED, encryption_key) if TAVILY_API_KEY_ENCRYPTED else os.getenv('TAVILY_API_KEY', '')

MAILGUN_API_KEY = ''
MAILGUN_DOMAIN = ''
MAILGUN_BASE_URL = 'https://api.mailgun.net'

# SQL Servers
DB_USER = DATABASE_UID
DB_PWD = DATABASE_PWD
DB_SERVER = DATABASE_SERVER
DB_NAME = DATABASE_NAME
DB_DRIVER = os.getenv('DATABASE_DRIVER', 'SQL Server')
CONNECTION_STRING = f"DRIVER={{SQL Server}};SERVER={DB_SERVER};DATABASE={DB_NAME};UID={DB_USER};PWD={DB_PWD}"

# WinRM Credentials
WINRM_USER = os.getenv('WINRM_USER')
WINRM_PWD = os.getenv('WINRM_PWD')
WINRM_DOMAIN = os.getenv('WINRM_DOMAIN')

# Windows Task Credentials
WINTASK_USER = os.getenv('WINTASK_USER')
WINTASK_PWD = os.getenv('WINTASK_PWD')
WINTASK_FOLDER = os.getenv('WINTASK_FOLDER')

# Tool Params
CUSTOM_TOOLS_FOLDER = os.path.join(os.getenv('APP_ROOT', _APP_ROOT), os.getenv('CUSTOM_TOOLS_FOLDER', 'tools'))
CORE_TOOLS_FILE = os.path.join(os.getenv('APP_ROOT', _APP_ROOT), 'core_tools.yaml')

# Phone API
PHONE_BASE_URL = _env_or_build('PHONE_BASE_URL', '')
PHONE_CALL_REQUEST = 'api/calls/' # os.getenv('PHONE_CALL_REQUEST')
PHONE_SOURCE = os.getenv('PHONE_SOURCE')
PHONE_DISPLAY_NAME = os.getenv('PHONE_DISPLAY_NAME')
API_AZURE_COMM_CONN_STR = _env_or_build('API_AZURE_COMM_CONN_STR', '')
API_AZURE_EMAIL_CONN_STR = _env_or_build('API_AZURE_EMAIL_CONN_STR', '')
API_AZURE_EMAIL_SENDER = _env_or_build('API_AZURE_EMAIL_SENDER', '')

# SMTP Configuration
SMTP_HOST = os.getenv('SMTP_HOST', 'smtp.office365.com')
SMTP_PORT = int(os.getenv('SMTP_PORT', '587'))
SMTP_USER = os.getenv('SMTP_USER')
SMTP_PASSWORD = os.getenv('SMTP_PASSWORD')
SMTP_USE_TLS = os.getenv('SMTP_USE_TLS', 'true').lower() in ['true', '1', 't', 'y', 'yes']
SMTP_FROM = os.getenv('SMTP_FROM', '')

# Email Provider Configuration
EMAIL_PROVIDER = os.getenv('EMAIL_PROVIDER', 'azure').lower()  # 'azure' or 'smtp'

# Misc Application Parameters
DEBUG_MODE = False
TIER_CACHE_TTL = 1800                                   # Cache TTL in seconds
USE_AGENT_API = True                                    # Determines if the agent API is used for all agent executions
AGENT_API_TIMEOUT = 300                                 # Timeout setting for making agent calls via API
TEXT_FILE_EXTENSIONS = os.getenv('TEXT_FILE_EXTENSIONS', '').split(',')
QUICK_JOB_EXECUTION_SCRIPT = os.path.join(_APP_ROOT, os.getenv('QUICK_JOB_EXECUTION_SCRIPT'))
QUICK_JOB_PATH = _APP_ROOT
SECRET_KEY = _env_or_build('FLASK_SECRET_KEY', 'change-me-before-production')
DOC_SEARCH_LIMIT = 800                                  # Max number of results to return from document search (NOTE: 1M input token limit)
DOC_CHECK_COMPLETENESS = False                          # (True) Only active when not returning additional pages automatically
DOC_RETURN_ADDITIONAL_PAGES = 0                         # (1) When > 0 deactivates check for document completeness
DOC_ENABLE_VECTOR_STORE = True                          # Save documents to local vector database (ChromaDB)
DOC_PROCESSING_TIMEOUT_MINUTES = int(os.getenv('DOC_PROCESSING_TIMEOUT_MINUTES', '120'))  # Timeout for large document uploads/processing (PDF 400+ pages)
DOC_MAX_UPLOAD_SIZE_MB = int(os.getenv('DOC_MAX_UPLOAD_SIZE_MB', '50'))                 # Max file size for knowledge uploads (MB). Covers PDFs, DOCX, images, etc.
USE_MODERN_NAV = os.getenv('USE_MODERN_NAV', 'True').lower() in ('true', '1', 'yes')  # Work/Build/Admin nav layout (False = legacy Core/Advanced/Experimental/Administration)
SHOW_LEGACY_DATA_CHAT = os.getenv('SHOW_LEGACY_DATA_CHAT', 'False').lower() in ('true', '1', 'yes')  # Show legacy Data Assistant Chat in nav (hidden by default, replaced by modern chat)
DOC_FIELD_METADATA_LIMIT = 100                          # Max number of fields to return from field metadata query
DEFAULT_INTERNET_SEARCH = 'tavily'                      # Default internet search API
DEFAULT_INTERNET_SEARCH_KEY = TAVILY_API_KEY            # Search provider key
ALLOW_INTERNET_SEARCH_FOR_NLQ = True                    # Set to False to disable internet search for NLQ
MAX_SEARCH_QUERY_TERMS = 5                              # Maximum number of terms in a search query
PRIORITIZE_DATES_IN_SEARCH = True                       # Focus search queries on finding event dates
MAX_CONVERSATION_LENGTH = 10                            # Max number of questions per conversation
AI_HUB_BYPASS_DOCUMENT_PROXY = False
USE_MINI_MODELS_WHEN_POSSIBLE = False
MINI_MODEL_REASONING_EFFORT = 'low'
OPENAI_REASONING_EFFORT = os.getenv('OPENAI_REASONING_EFFORT', 'low')  # none, low, medium, high, xhigh
DATA_AGENT_FALLBACK_RESPONSE = "I'm sorry, I encountered an issue processing your request. Please try a different question or contact support if the problem persists."
GENERAL_AGENT_FALLBACK_RESPONSE = "I'm sorry, I encountered an issue processing your request. Please try a different question or contact support if the problem persists."
WORKFLOW_AGENT_FALLBACK_RESPONSE = "I'm having trouble processing that request. This could be due to content filtering or message complexity. Could you try rephrasing your request or breaking it into smaller steps?"
SHOW_DOCUMENT_FEATURES = True                           # Set to False to hide document processing features
SHOW_WORKFLOW_FEATURES = True                           # Set to False to hide workflow features
AGENT_ENVIRONMENTS_ENABLED = True                       # Set to False to hide environment features
SHOW_DATA_AGENT_TEST_FEATURES = False                   # Set to False to hide data agent stress test features
DOC_ALLOWED_EXTENSIONS = {'pdf', 'docx', 'doc', 'txt', 'csv', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'bmp', 'gif', 'tiff', 'tif'}
LOG_MAX_BYTES = 1024 * 1024 * 10                        # Add * 10 = 10MB
LOG_BACKUP_COUNT = 5
LOG_LEVEL = os.getenv('LOG_LEVEL')                      # You can set LOG_LEVEL as 'DEBUG', 'INFO', 'WARNING', 'ERROR', or 'CRITICAL'
DEFAULT_RECENT_CONVERSATION_WINDOW = 5                  # Number of recent entries in conversation to show for context
JOB_SCHEDULER_TIMEZONE = 'UTC'                          # Timezone of dates and times coming from the main config database (this should not be changed)
VECTOR_EMBEDDING_MODEL = 'openai'                      # default/onnx/openai/minilm/hash (do not use hash)
USE_APSCHEDULER_FOR_QUICKJOBS = True                    # Set to False to use Windows Task Scheduler for quick jobs
DOC_TYPE_DETECTION_PAGES_TO_USE = [0,1]                 # Pages to use for document type detection
AGENT_ENVIRONMENTS_ENABLED = True                       # Enabled/disable agent environments feature
SMART_RENDER_ENABLED = True                             # Enabled/disable smart render for advanced output display to users
SMART_RENDER_CONTENT_LIMIT = 100000                     # DEPRECATED AS CONTENT IS BASED ON OUTPUT TOKENS: Character limit for content to smart render (s/b based on input token limits)
PKG_MGR_INSTALL_BASE = False                            # Enable/disable installation of base packages w/ environments (not needed)
PKG_MGR_INFRASTRUCTURE = {'pip', 'setuptools', 'wheel', 'pkg-resources'}        # Infrastructure packages
PKG_MGR_INSTALL_TIMEOUT = 900
ENVIRONMENT_PROCESSES_TIMEOUT = 300
ENABLE_RICH_CONTENT_RENDERING = True                    # Rich Content Rendering for Data Assistants
USE_FORMATTING_AWARE_ANALYTICAL_CHECK = True            # Uses enhanced data dictionary data for analytical processing (Only use if needed)
COLUMN_FORMAT_MATCHING_STRATEGY = 'ai'                  # Strategy for matching dataset columns to source columns: 'ai', 'fuzzy', or 'default'
USE_LLM_CHART_GENERATION = os.getenv('USE_LLM_CHART_GENERATION', 'false').lower() in ['true', '1', 't', 'y', 'yes']  # Force LLM spec-based chart generation, bypassing PandasAI for charts
SHOW_EXPERIMENTAL_FEATURES = False                      # Set to False to hide experimental features that are still under development

# ─── Solutions Gallery (experimental) ───────────────────────────────────────
# Directory for bundled first-party solutions shipped with the app.
SOLUTIONS_BUILTIN_DIR = os.getenv('SOLUTIONS_BUILTIN_DIR',
    os.path.join(_APP_ROOT, 'solutions_builtin'))
# Directory where authored solution drafts are persisted per tenant.
SOLUTIONS_DRAFTS_DIR = os.getenv('SOLUTIONS_DRAFTS_DIR',
    os.path.join(_APP_ROOT, 'data', 'solutions_drafts'))
# URL of a remote catalog manifest (optional). Empty disables remote.
SOLUTIONS_CATALOG_URL = os.getenv('SOLUTIONS_CATALOG_URL', '')
# Where downloaded remote solution bundles are cached.
SOLUTIONS_CACHE_DIR = os.getenv('SOLUTIONS_CACHE_DIR',
    os.path.join(_APP_ROOT, 'data', 'solutions_cache'))
USE_MODERN_CHAT_UI = os.getenv('USE_MODERN_CHAT_UI', 'true').lower() in ['true', '1', 't', 'y', 'yes']  # Set to False to use legacy assistants/data_assistants pages
WORKFLOW_TRAINING_CAPTURE_ENABLED = os.getenv('WORKFLOW_TRAINING_CAPTURE_ENABLED', 'true').lower() in ['true', '1', 't', 'y', 'yes']

# -----------------------------------------------------------------------------
# Workflow Command Validator (deterministic pre-pass + LLM fallback)
# -----------------------------------------------------------------------------
# Master switch for the deterministic pre-pass in workflow_command_validator.py.
# When True, deterministic checks run first and silently fix issues that have
# unambiguous fixes (e.g. duplicate connections, missing start node, integration
# id passed as a name). The LLM validator only runs as a fallback for issues
# the deterministic path cannot resolve, or if the deterministic path raises.
# When False, validation skips the deterministic pre-pass entirely and uses
# the original LLM-only behavior. Flip to False as a quick rollback if the new
# code path misbehaves.
WORKFLOW_VALIDATOR_DETERMINISTIC_ENABLED = os.getenv('WORKFLOW_VALIDATOR_DETERMINISTIC_ENABLED', 'true').lower() in ['true', '1', 't', 'y', 'yes']
# When True, the deterministic fixer also acts on warning-severity issues, not
# just hard errors. When False (default), warnings are reported but never
# auto-fixed and never trigger the LLM fallback on their own.
WORKFLOW_VALIDATOR_FIX_WARNINGS = os.getenv('WORKFLOW_VALIDATOR_FIX_WARNINGS', 'false').lower() in ['true', '1', 't', 'y', 'yes']
# When True, always run the LLM validator after the deterministic pre-pass even
# if the deterministic pre-pass found and fixed everything. Use as a safety
# belt if you want a second opinion on every workflow. When False (default),
# the LLM is only called when the deterministic pre-pass leaves unresolved
# issues or raises an exception.
WORKFLOW_VALIDATOR_ALWAYS_RUN_LLM = os.getenv('WORKFLOW_VALIDATOR_ALWAYS_RUN_LLM', 'false').lower() in ['true', '1', 't', 'y', 'yes']

# Two-Stage Workflow Agent Architecture
USE_TWO_STAGE_ARCHITECTURE = os.getenv('USE_TWO_STAGE_ARCHITECTURE', 'false').lower() == 'true'
COMMAND_GENERATOR_MODEL = os.getenv('COMMAND_GENERATOR_MODEL', '')  # e.g., 'ft:gpt-4.1-mini-2025-04-14:your-org::abc123'
COMMAND_GENERATOR_DEPLOYMENT = os.getenv('COMMAND_GENERATOR_DEPLOYMENT', '')  # Azure deployment name if using Azure
MAX_GENERAL_AGENT_ITERATIONS = 10                       # Prevents runaway tool calls
WORKFLOW_EXECUTION_TIMEOUT = 3600                       # Timeout for workflow executions over API
MAX_ATTACHMENT_SIZE_MB = 100                            # Max size of email attachment for text extraction
MAX_ATTACHMENT_CHARS = 500000                           # Max characters returned from text extraction for email attachments
SMART_RENDER_HYBRID_ENABLED = True                      # Enable smart render with both deterministic and AI generated output
SMART_RENDER_HYBRID_USE_MINI_MODEL = True               # Use mini or full models
SMART_RENDER_HYBRID_ENABLE_AI_INSIGHTS = True           # Include AI insights (increases response time)
SMART_RENDER_HYBRID_ENABLE_VIZ_SUGGESTIONS = False      # This output is not actually used
SMART_RENDER_HYBRID_AI_INSIGHTS_MAX_ROWS = 10000        # Max data to show AI for insights
SMART_RENDER_HYBRID_MAX_TABLE_DISPLAY_ROWS = 100000     # Max rows to show user
SMART_RENDER_HYBRID_MAX_CONTENT_FOR_AI = 250000         # Max chars that can be provided to AI
MAX_LOG_CHARS = 1000                                    # Max chars that can be written to log files per entry
SMART_CHANGE_BATCH_SIZE = 25                            # Max numbers of lines evaluated by AI in Excel updates
SMART_CHANGE_INCLUDE_CONTEXT = False                    # Whether to include context fields when evaluating changes (can cause frequent changes if true)

# Excel Processing
EXCEL_AI_STRUCTURE_DETECTION = True                     # Enable AI-guided structure detection for Excel files
EXCEL_MAX_ROWS_PER_SHEET = 5000                         # Maximum rows to extract per sheet
EXCEL_STRUCTURE_SAMPLE_ROWS = 20                        # Number of rows to sample for structure detection
EXCEL_STRUCTURE_MAX_TOKENS = 1024                       # Max tokens for structure detection response

# Excel Live Data Source (Phase 1)
EXCEL_KNOWLEDGE_FILES_DIR = 'knowledge_files'           # Persistent directory for Excel files
EXCEL_QUERY_MAX_ROWS = 500                              # Max rows returned by read_excel_data
EXCEL_QUERY_DEFAULT_ROWS = 100                          # Default rows when no limit specified
EXCEL_METADATA_SAMPLE_ROWS = 5                          # Sample rows in metadata profile
EXCEL_METADATA_MAX_STATS_COLUMNS = 50                   # Max numeric columns for stats
EXCEL_CHART_MAX_DATA_POINTS = 1000                      # Max data points for charts
EXCEL_AGGREGATION_MAX_ROWS = 50000                      # Max source rows for aggregation

# Data Parameters
LLM_ROW_LIMIT = os.getenv('LLM_ROW_LIMIT')
LLM_CHARACTER_LIMIT = os.getenv('LLM_CHARACTER_LIMIT')
LLM_TEMPERATURE = os.getenv('LLM_TEMPERATURE')
LLM_SEED = os.getenv('LLM_SEED')
LLM_ENGINE_LOG = _resolve_log_path('LLM_ENGINE_LOG', 'data_engine_log.txt')
LLM_QUERY_LOG  = _resolve_log_path('LLM_QUERY_LOG',  'query_engine_log.txt')
LLM_LOGICAL_QUERY_INSTRUCTION = (
    ' - Additional instructions: '
    + 'Convert all NaN values to zero or blank '
    + ' - CRITICAL: When generating Python (Pandas) code involving date columns: '
    'Assume database columns like "data_date" are already properly typed (datetime.date or datetime64[ns]). '
    'If the data is datetime.date, compare directly using datetime.date objects. '
    'DO NOT use the .dt accessor unless absolutely necessary. '
    'Only use pd.to_datetime() if the column is strings or objects. '
    'Example: import datetime; today = datetime.date.today(); '
    'target_day = datetime.date(today.year, 12, 25); '
    'filtered = df[df["data_date"] == target_day]. '
    'Always import datetime using from datetime import date, and use date(...) instead of datetime.date(...). This prevents name collisions in shared execution environments.'
    ' - For pivot tables, use the requested row field (e.g., brand) as the index, and always apply `.reset_index()` to ensure row labels (like brand names) are preserved as columns.'

)

LLM_PANDAS_AGENT_DESCRIPTION = os.getenv('LLM_PANDAS_AGENT_DESCRIPTION')
LLM_PANDAS_CODE_REGEN_SYSTEM = os.getenv('LLM_PANDAS_CODE_REGEN_SYSTEM')
LLM_PANDAS_CODE_REGEN_PROMPT = os.getenv('LLM_PANDAS_CODE_REGEN_PROMPT')

# Data Agents
DISPLAY_ROW_LIMIT = 100
DISPLAY_COLUMN_LIMIT = 20
GENERAL_CHAT_AI_PROCESSING_ROW_LIMIT = 50               # AI processing row limit - beyond this datasets will be injected directly and bypass LLM (using data agents via general agent communication)
REFINE_TABLE_SELECTION = True
CHECK_FOR_MISSING_HEADERS = True
CONFIDENCE_THRESHOLD_REQUESTING_MORE_INFO_INITIAL = 89  # Only request more info from user if above threshold (and need_info==yes)
CONFIDENCE_THRESHOLD_REQUESTING_MORE_INFO = 89          # Only request more info from user if below threshold (and sufficient_info==no)
CONFIDENCE_THRESHOLD_FOR_ANALYTICAL_PROCESSING = 86     # Only use analytical engine if above threshold (and dataset_sufficient==no)
REFINE_ZERO_ROW_RESPONSES = True                        # If no data is returned and True, the AI will 'cleanse' the response
ATTEMPT_TO_RESPOND_ON_USERS_BEHALF = True               # If True the AI will attempt to fulfill requests from the AI for more info
DATA_AGENT_ERROR_CATEGORIES = {
        'database_connection': 'Unable to connect to the database. Please try again later or contact support.',
        'query_syntax': 'There was an issue with the database query. Our team has been notified.',
        'insufficient_permissions': 'You do not have sufficient permissions to access this data.',
        'invalid_input': 'Your input contains invalid characters or format.',
        'empty_result': 'No results found for your query. Please try different search terms.',
        'timeout': 'The request took too long to process. Please try a simpler query.',
        'ai_confidence': 'I am not confident in providing an accurate answer to this question.',
        'unknown': 'An unexpected error occurred. Our team has been notified.'
    }

DATA_AGENT_CAUTION_LEVELS = {
        'low': {'confidence_threshold': 0.3, 'ask_for_clarification_threshold': 0.4},
        'medium': {'confidence_threshold': 0.5, 'ask_for_clarification_threshold': 0.6},
        'high': {'confidence_threshold': 0.7, 'ask_for_clarification_threshold': 0.75},
        'very_high': {'confidence_threshold': 0.85, 'ask_for_clarification_threshold': 0.9},
    }

DATA_AGENT_DEFAULT_CAUTION_LEVELS = {
        'low': {
            'description': 'Makes more assumptions, fewer clarification requests',
            'confidence_threshold': 0.3,
            'clarification_threshold': 0.4,
            'max_assumption_count': 3,
            'allow_extrapolation': True
        },
        'medium': {
            'description': 'Balanced approach with reasonable verification',
            'confidence_threshold': 0.5,
            'clarification_threshold': 0.6,
            'max_assumption_count': 2,
            'allow_extrapolation': True
        },
        'high': {
            'description': 'Cautious approach with more verification',
            'confidence_threshold': 0.7,
            'clarification_threshold': 0.75,
            'max_assumption_count': 1,
            'allow_extrapolation': False
        },
        'very_high': {
            'description': 'Maximum caution, minimal assumptions',
            'confidence_threshold': 0.85,
            'clarification_threshold': 0.9,
            'max_assumption_count': 0,
            'allow_extrapolation': False
        }
    }

# Default caution level
DEFAULT_CAUTION_LEVEL = 'medium'

# Threshold for deciding whether to use analytical processing
CONFIDENCE_THRESHOLD_FOR_ANALYTICAL_PROCESSING = 70  # 0-100

# Threshold for requesting more information from the user
CONFIDENCE_THRESHOLD_REQUESTING_MORE_INFO = 60  # 0-100

# Caution System Configuration
ENABLE_CAUTION_SYSTEM = False  # Set to False to disable caution features

# Whether to filter technical details from responses (using ResponseFilter)
ENABLE_RESPONSE_FILTER = True

# Agent Knowledge Management
ENABLE_AGENT_KNOWLEDGE_MANAGEMENT = False

# Token warning system settings
ENABLE_TOKEN_WARNING = False
CHARS_PER_TOKEN = 4
TOKEN_WARNING_THRESHOLD = 6000
TOKEN_WARNING_MESSAGE = "⚠️ Your request is estimated to use {token_count} tokens, which may result in failed requests or slower processing. Consider shortening your message or being more specific if possible."

# Workflow settings
WORKFLOW_DOC_DO_NOT_SAVE_DEFAULT = True         # Save processed documents when run in a workflow
WORKFLOW_DOC_EXTRACT_FIELDS_DEFAULT = False     # Extract field level data from documents when run in a workflow (performance setting)
WORKFLOW_DOC_DETECT_TYPE_DEFAULT = False        # Detect document type when run in a workflow (performance setting)
WORKFLOW_DOC_STREAM_AT_SIZE = 3                 # MB file size threshold at which to start streaming

############################
##### ENHANCED DOCS    #####
############################
# Document search intelligence settings
DOC_API_REQUESTS_TIMEOUT = 300              # Timeout for API requests
DOC_INTELLIGENT_MAX_CONTEXT_TOKENS = 100000 # When to summarize due to size
DOC_TOKENS_PER_PAGE_ESTIMATE = 800         # Used for determining batch sizes (higher = more batches)
DOC_CHARS_PER_TOKEN = 4                    # For token estimation  
DOC_SMALL_RESULT_THRESHOLD = 25            # Below this = definitely show all
DOC_LARGE_RESULT_THRESHOLD = 100           # Above this = definitely summarize
DOC_ABSOLUTE_MAX_RESULTS = 500             # Prevent DB overload
DOC_INCLUDE_KEY_FIELDS_IN_METADATA = False # Determines if key fields should be found using basic logic like %id%, %code%, etc. (not sure if this adds value)
DOC_INCLUDE_FIELD_SAMPLES_VALUES = False   # Determines if sample values are included in document_universe_metadata (takes time and might not be used)
DOC_FIELD_SAMPLE_VALUES_COUNT = 3          # Number of sample values to include for each field
DOC_INCLUDE_FIELD_USAGE_STATS = False      # Determines if field usage stats are in document_universe_metadata (takes time and might not be useless)
DOC_USE_AI_SELECTED_FIELDS = True          # Use AI selected fields for data retrieval
DOC_LIMIT_SEARCH_AI_SELECTED_FIELDS = False # *Use AI selected fields to filter document search results (Limits search results to only documents with the selected fields)
DOC_INCLUDE_AI_SELECTED_FIELDS_IN_RESULT = True # Include AI selected fields in search results (uses more tokens)
DOC_USE_RECALL_PROMPTING_FOR_AI_FIELD_SELECTION = True # Use recall prompt template over precision prompt in sys_prompts
DOC_INCLUDE_COUNTS_IN_AI_FIELD_DATA = False         # This will include field counts in metadata but this can influence the AI to limit the fields it chooses (low counts are not always bad)
DOC_IGNORE_FIELD_FILTERS = False                    # Ignore field filters when searching for documents (useful if field matching is not working due to date formatting issues, etc.)
DOC_GET_ADDITIONAL_DOCUMENT_INFO = False            # Get additional document info - processed_at, reference_number, customer_id, vendor_id, document_date
DOC_USE_MINI_MODEL_FOR_AI_FIELD_SELECTION = True    # Uses a mini model instead of core model for ai field selection (reduces token usage on core model)
DOC_INCLUDE_FULL_PAGE_IN_CHUNK_RESULTS = False      # If True chunks are only used to find pages and full page text is returned to the AI instead of just chunks
VECTOR_USE_SMART_CHUNKING = True                    # Smart chunking on/off switch
VECTOR_SMART_CHUNKING_MAX_CHARS = 128000            # Max context window for LLM chunking (can be ~1M tokens)

# *IMPORTANT* If the AI is not correctly identifying and finding certain date fields, add them to this list so they can be properly searched
DOC_DATE_FIELD_KEYWORDS = ['date', 'time', 'timestamp', 'created', 'modified', 'updated', 'processed', 'expiration', 'expires', 'due', 'start', 'end', 'begin', 'finish', 'commencement', 'termination', 'effective']

DOC_IGNORE_FIELDS_IN_FIELD_METADATA = "'page_number', 'page_count', 'page_id', 'document_id', 'filename', 'document_type'"
DOC_KNOWLEDGE_SPECIAL_INSTRUCTIONS = "First decide on your response to the user and then add all document ID and filename to your knowledge base using your knowledge management tools. This is so you do not solely base your answer on the data you just added to the knowledge base. Be sure to always include clickable_link to the documents in your response."
DOC_INCLUDE_SNIPPET_IN_RESULT = True        # *IMPORTANT*: Include snippet for context (uses more tokens but limits context if not enabled - try to limit the snippet w/ other settings before disabling if running into token limits)
DOC_TOP_N_FIELDS_INCLUDED_IN_RESULTS = 200  # *IMPORTANT*: These are the fields the AI will "see" in the results - each document will typically add new useless fields therefore cannot include everything
DOC_PAGE_TEXT_LIMIT_IN_RESULTS = 500        # *IMPORTANT*: This limits the page text results the AI will see. Limit this for large documents to avoid token limits or use summary settings below.

# Additional note that gets added to the user-specific document context injection prompt
DOC_USER_SPECIFIC_PROMPT_NOTE = "\nNote: Documents shown as a 'Document Group' were uploaded together and are likely related.\n"          

# Enable/disable fast PDF extraction (default: True)
DOC_USE_FAST_PDF_EXTRACTION = True

# Minimum characters expected per page for quality validation
# If fast extraction produces less than this, AI extraction is used instead
DOC_FAST_PDF_MIN_CHARS_PER_PAGE = 250

# Whether to always try fast extraction first, even for PDFs detected as scanned
# Setting to False will skip fast extraction for clearly scanned PDFs
DOC_FAST_PDF_ALWAYS_TRY_FAST = False

# Maximum pages per PDF chunk for schema extraction
# Claude's API has a hard limit of 100 pages per PDF document
DOC_SCHEMA_EXTRACTION_MAX_PAGES = 100

# Number of pages to overlap between chunks
DOC_SCHEMA_EXTRACTION_CHUNK_OVERLAP = 3

# Enable verbose logging for chunked schema extraction
DOC_SCHEMA_EXTRACTION_VERBOSE_LOGGING = True

# AI Post-Processing for Intelligent Search
AI_FILTER_MAX_RESULTS_TO_ANALYZE = 100     # Max results to send to AI (token management)
AI_FILTER_ENABLE_BY_DEFAULT = True         # Enable AI post-processing by default
AI_FILTER_SIMPLE_THRESHOLD = 5             # Use simple filtering for result sets <= this size

# ============================================================================
# DOCUMENT SUMMARIZATION CONFIGURATION
# ============================================================================
# Enable/disable automatic summarization during document processing
DOC_ENABLE_AUTO_SUMMARIZATION = False                   # Create document summaries during initial processing
DOC_SEARCH_ENABLE_SUMMARIES = False                     # Global toggle for summary usage in search
DOC_SEARCH_DEFAULT_SUMMARY_TYPE = 'detailed'            # Default summary type to use for search

# Default summary types to generate automatically during document processing
# Options: 'standard', 'brief', 'detailed', 'bullet_points', 'executive'
DOC_AUTO_SUMMARY_TYPES = ['detailed']

DOC_ANTHROPIC_PROXY_MAX_RETRIES = 3
DOC_ANTHROPIC_PROXY_RETRY_DELAY_BASE = 1.0
DOC_ANTHROPIC_PROXY_RETRY_DELAY_MAX = 8.0
DOC_ANTHROPIC_PROXY_RETRY_STATUS_CODES = [429, 500, 502, 503, 504, 529]

# Special instructions for different document types (optional)
DOC_SUMMARY_SPECIAL_INSTRUCTIONS = {
    'invoice': '',
    'contract': '',
    'email': '',
    # Add more as needed
}

# Document search summary settings
DOC_SEARCH_USE_SUMMARIES_BY_DOCTYPE = {
    'invoice': False,
    'contract': False, 
    'email': False,
    # Add more document types as needed
}

# Text Chunking Configuration
VECTOR_CHUNK_SIZE = 512                                 # Target chunk size in characters
VECTOR_CHUNK_OVERLAP = 64                               # Overlap between chunks in characters
VECTOR_ENABLE_CHUNKING = True                           # Enable/disable chunking

# Text Splitter Configuration (using LangChain)
VECTOR_SPLITTER_TYPE = 'recursive_character'            # recursive_character, token, markdown, html, python

# For chat/retrieval context
VECTOR_SEARCH_RESULTS_CHAR_LIMIT_FOR_AI = 300000        # Character limit when formatting document search results for AI prompts
VECTOR_SEARCH_RESULTS_MIN_SCORE_FOR_AI = 0.25           # Minimum relevance score for chunk results to be included in document search results
VECTOR_SEARCH_RESULTS_RESULT_LIMIT_FOR_AI = 999         # Maximum results that can be returned by the document search

# NLQ Performance Settings
USE_COMBINED_ANALYSIS = False                           # Combines multiple prompts into a single analysis for performance gain (LEAVE FALSE - CURRENTLY AI LOSES CONTEXT AND NO REAL PERFORMANCE GAINS)

# Knowledge API Configuration
KNOWLEDGE_API_HOST = '0.0.0.0'
KNOWLEDGE_API_PORT = int(os.getenv('HOST_PORT', 5001)) + 50
KNOWLEDGE_API_DEBUG = False
KNOWLEDGE_API_TIMEOUT = 60
LOG_DIR_KNOWLEDGE = os.path.join(_APP_ROOT, 'logs', 'knowledge_api.log')
AZURE_EMAIL_TIMEOUT = 900
ENABLE_WORKFLOW_ASSISTANT = False                        # Legacy Workflow Assistant Feature Flag - Set to False to disable
CLOUD_API_REQUESTS_TIMEOUT = 30

# Smart Knowledge Retrieval Configuration
KNOWLEDGE_BRUTE_FORCE_MAX_CHARS = int(os.getenv('KNOWLEDGE_BRUTE_FORCE_MAX_CHARS', 500_000))  # Below this: dump all text (brute force)
KNOWLEDGE_VECTOR_COLLECTION = 'agent_knowledge'          # Separate ChromaDB collection for knowledge docs (isolated from system document search)
KNOWLEDGE_VECTOR_TOP_K = int(os.getenv('KNOWLEDGE_VECTOR_TOP_K', 10))  # Top-K chunks for needle queries
KNOWLEDGE_SUMMARY_MAX_CHARS = int(os.getenv('KNOWLEDGE_SUMMARY_MAX_CHARS', 500))  # Per-document structured summary cap
KNOWLEDGE_ENABLE_SUMMARIES = os.getenv('KNOWLEDGE_ENABLE_SUMMARIES', 'True').lower() == 'true'  # Generate summaries at upload
KNOWLEDGE_ENABLE_SMART_RETRIEVAL = os.getenv('KNOWLEDGE_ENABLE_SMART_RETRIEVAL', 'True').lower() == 'true'  # Enable smart retrieval (vs always brute force)
KNOWLEDGE_ENABLE_TRACE = os.getenv('KNOWLEDGE_ENABLE_TRACE', 'False').lower() == 'true'  # Enable SKR trace logging to logs/skr_trace.txt
KNOWLEDGE_ROUTER_MODEL = os.getenv('KNOWLEDGE_ROUTER_MODEL', 'claude-haiku')  # Cheap model for query routing

EMAIL_DISPATCHER_ENABLED = True    # Auto-start with service
EMAIL_POLL_INTERVAL = 60           # Seconds between polls

# Function to override config parameters from user_config.py if it exists os.getcwd()
def load_user_config():
    user_config_path = os.path.join(_APP_ROOT, "user_config.py")
    if os.path.exists(user_config_path):
        try:
            # Create a namespace to execute the user_config in
            user_config_namespace = {}
            with open(user_config_path, "r") as f:
                code = compile(f.read(), user_config_path, 'exec')
                exec(code, user_config_namespace)
            
            # Update the current module's globals with values from user_config
            import sys
            current_module = sys.modules[__name__]
            for key, value in user_config_namespace.items():
                if not key.startswith('__'):  # Skip special Python variables
                    setattr(current_module, key, value)
                    print(f"Override applied: {key} = {value}")
        except Exception as e:
            print(f"Failed to load user_config: {e}")

# Load user-defined configuration parameters
load_user_config()
