
import os
from dotenv import load_dotenv
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
import base64

# Load .env early so ENCRYPTION_SECRET is available when this module
# is imported before the caller's own load_dotenv() call.
load_dotenv()

# Optional bundled credentials module (generated by scripts/generate_build_config.py
# and included in PyInstaller client builds). Gitignored, not present in dev.
try:
    import _build_config as _bc
except ImportError:
    _bc = None


def _env_or_build(name, default=''):
    """Resolve a credential per-variable:
    1. os.getenv(name) wins if set to a non-empty value (.env override)
    2. _build_config.<name> supplies the value otherwise (bundled default)
    3. `default` as last resort
    """
    v = os.getenv(name)
    if v:
        return v
    if _bc is not None:
        v = getattr(_bc, name, None)
        if v:
            return v
    return default


APP_SECRET = _env_or_build('ENCRYPTION_SECRET', '')

# Decryption functionality
def generate_key(password, salt=None):
    if salt is None:
        salt = _env_or_build('ENCRYPTION_SALT', 'default-salt').encode()
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=100000,
    )
    key = base64.urlsafe_b64encode(kdf.derive(password.encode()))
    return key

def decrypt_value(encrypted_value, key):
    try:
        cipher = Fernet(key)
        return cipher.decrypt(encrypted_value.encode()).decode()
    except Exception as e:
        print(f"Decryption error: {str(e)}")
        return None

ENCRYPTION_KEY = generate_key(APP_SECRET)

def encrypt_data(data: str) -> str:
    """Encrypt sensitive data"""
    f = Fernet(ENCRYPTION_KEY) 
    encrypted = f.encrypt(data.encode())
    return base64.b64encode(encrypted).decode()

def decrypt_data(encrypted_data: str) -> str:
    """Decrypt sensitive data"""
    f = Fernet(ENCRYPTION_KEY) 
    encrypted_bytes = base64.b64decode(encrypted_data.encode())
    decrypted = f.decrypt(encrypted_bytes)
    return decrypted.decode()
