"""
generate_build_config.py
------------------------
Build-time script that reads credential values from .env and writes them into
a gitignored _build_config.py file at the repo root.

_build_config.py is then bundled by PyInstaller into client builds (as compiled
bytecode) so that credentials can be present on client machines WITHOUT shipping
them as plaintext in .env.

Runtime resolution order for the values listed below is per-variable:
    1. os.getenv(name)        - reads .env (allows per-machine overrides)
    2. _build_config.<name>   - bundled fallback (default credentials)
    3. code default           - usually ''

Everything else in .env (HOST_PORT, WINTASK_*, etc.) is NOT bundled.

Usage:
    python scripts/generate_build_config.py

Run this BEFORE `pyinstaller *.spec` in the build pipeline.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# Add repo root to sys.path so we can import dotenv even when run from /scripts
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

try:
    from dotenv import dotenv_values
except ImportError:
    print("ERROR: python-dotenv not installed. Run: pip install python-dotenv", file=sys.stderr)
    sys.exit(1)


# =============================================================================
# ALLOW-LIST — the single source of truth for what gets bundled.
# Exactly the set of hardcoded-credential values that were moved out of
# config.py / encrypt.py into .env for the open source release.
# Do NOT add operational config (HOST_PORT, LOG_LEVEL, etc.) to this list.
# =============================================================================
ALLOWED_KEYS = [
    # Encryption (used by encrypt.py to decrypt the _ENCRYPTED blobs below)
    "ENCRYPTION_SECRET",
    "ENCRYPTION_SALT",

    # Database
    "DATABASE_SERVER",
    "DATABASE_NAME",
    "DATABASE_UID",
    "DATABASE_PWD",

    # Cloud database
    "CLOUD_DATABASE_SERVER",
    "CLOUD_DATABASE_NAME",
    "CLOUD_DATABASE_UID",
    "CLOUD_DATABASE_PWD",

    # Azure OpenAI
    "AZURE_OPENAI_BASE_URL",
    "AZURE_OPENAI_API_KEY_ENCRYPTED",
    "AZURE_OPENAI_BASE_URL_ALTERNATE",
    "AZURE_OPENAI_API_KEY_ALTERNATE_ENCRYPTED",
    "AZURE_OPENAI_BASE_URL_MINI",
    "AZURE_OPENAI_API_KEY_ENCRYPTED_MINI",

    # Other LLM providers
    "OPENAI_API_KEY_ENCRYPTED",
    "ANTHROPIC_API_KEY_ENCRYPTED",
    "TAVILY_API_KEY_ENCRYPTED",

    # Azure Communication Services
    "API_AZURE_COMM_CONN_STR",
    "API_AZURE_EMAIL_CONN_STR",
    "API_AZURE_EMAIL_SENDER",

    # Phone API
    "PHONE_BASE_URL",

    # Flask
    "FLASK_SECRET_KEY",
]

# =============================================================================
# LLM-ONLY subset — bundled LOOSE at {app}\_build_config.py for the source-run
# Browser Use service (Strategy B), which imports _build_config from the install
# root to resolve the Azure/OpenAI LLM keys. It must NOT carry the DB password,
# comm-service connection strings, Flask secret, etc. (browser-use never needs
# them, and the loose file is a readable .py on the client disk). ENCRYPTION_
# SECRET/SALT are required here so encrypt.py can decrypt the *_ENCRYPTED blobs.
# The FULL file above is still bundled INSIDE every frozen exe by PyInstaller;
# frozen services import their baked copy before {app} joins sys.path, so this
# trimmed loose copy only ever shadows for the (source-run) browser-use service.
# =============================================================================
LLM_ONLY_KEYS = [
    "ENCRYPTION_SECRET",
    "ENCRYPTION_SALT",
    "AZURE_OPENAI_BASE_URL",
    "AZURE_OPENAI_API_KEY_ENCRYPTED",
    "AZURE_OPENAI_BASE_URL_ALTERNATE",
    "AZURE_OPENAI_API_KEY_ALTERNATE_ENCRYPTED",
    "AZURE_OPENAI_BASE_URL_MINI",
    "AZURE_OPENAI_API_KEY_ENCRYPTED_MINI",
    "OPENAI_API_KEY_ENCRYPTED",
    "ANTHROPIC_API_KEY_ENCRYPTED",
]


def _write_config(output_path: Path, keys: list[str], env_values: dict,
                  basename: str, note: str) -> tuple[int, list[str]]:
    """Write a _build_config-shaped module containing exactly the present `keys`.
    Returns (count_written, missing_keys)."""
    present: list[tuple[str, str]] = []
    missing: list[str] = []
    for key in keys:
        val = env_values.get(key)
        if val is not None and val != "":
            present.append((key, val))
        else:
            missing.append(key)

    header = (
        "# ============================================================================\n"
        f"# {basename}\n"
        "# Auto-generated by scripts/generate_build_config.py\n"
        "#\n"
        "# DO NOT COMMIT. DO NOT EDIT BY HAND.\n"
        f"# {note}\n"
        "# Gitignored. Regenerated from .env before each build.\n"
        "# ============================================================================\n"
        "\n"
    )
    lines = [header]
    for key, val in present:
        # Use repr() so quotes, backslashes, newlines, etc. are safely escaped.
        lines.append(f"{key} = {val!r}\n")
    output_path.write_text("".join(lines), encoding="utf-8")
    return len(present), missing


def main() -> int:
    env_path = _REPO_ROOT / ".env"

    if not env_path.exists():
        print(f"ERROR: .env not found at {env_path}", file=sys.stderr)
        return 1

    # dotenv_values returns exactly what's in the file, without merging os.environ
    env_values = dotenv_values(env_path)

    # 1) FULL build config — bundled INSIDE the frozen exes by PyInstaller.
    full_path = _REPO_ROOT / "_build_config.py"
    n_full, miss_full = _write_config(
        full_path, ALLOWED_KEYS, env_values, "_build_config.py",
        "Contains production credentials bundled into PyInstaller client builds.")
    print(f"Wrote {full_path.name}")
    print(f"  Included:  {n_full} / {len(ALLOWED_KEYS)} allow-listed values")
    if miss_full:
        print(f"  Missing:   {len(miss_full)} (skipped - not in .env): {', '.join(miss_full)}")

    # 2) LLM-ONLY build config — shipped LOOSE at {app}\_build_config.py (via the
    #    installer's DestName rename) for the source-run Browser Use service. No
    #    DB password / comm-service / Flask secret on the client's readable disk.
    client_path = _REPO_ROOT / "_build_config_client.py"
    n_llm, miss_llm = _write_config(
        client_path, LLM_ONLY_KEYS, env_values, "_build_config_client.py (LLM keys only)",
        "LLM keys only - shipped loose to clients for the source-run browser-use service.")
    print(f"Wrote {client_path.name}")
    print(f"  Included:  {n_llm} / {len(LLM_ONLY_KEYS)} LLM-only values")
    if miss_llm:
        print(f"  Missing:   {len(miss_llm)} (skipped - not in .env): {', '.join(miss_llm)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
