"""
generate_build_config.py
------------------------
Build-time script that reads credential values from .env and writes them into
a gitignored _build_config.py file at the repo root.

_build_config.py is then bundled by PyInstaller into client builds (as compiled
bytecode) so that credentials can be present on client machines WITHOUT shipping
them as plaintext in .env.

Runtime resolution order for the values listed below is per-variable:
    1. os.getenv(name)        - reads .env (allows per-machine overrides)
    2. _build_config.<name>   - bundled fallback (default credentials)
    3. code default           - usually ''

Everything else in .env (HOST_PORT, WINTASK_*, etc.) is NOT bundled.

Usage:
    python scripts/generate_build_config.py

Run this BEFORE `pyinstaller *.spec` in the build pipeline.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# Add repo root to sys.path so we can import dotenv even when run from /scripts
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

try:
    from dotenv import dotenv_values
except ImportError:
    print("ERROR: python-dotenv not installed. Run: pip install python-dotenv", file=sys.stderr)
    sys.exit(1)


# =============================================================================
# ALLOW-LIST — the single source of truth for what gets bundled.
# Exactly the set of hardcoded-credential values that were moved out of
# config.py / encrypt.py into .env for the open source release.
# Do NOT add operational config (HOST_PORT, LOG_LEVEL, etc.) to this list.
# =============================================================================
ALLOWED_KEYS = [
    # Encryption (used by encrypt.py to decrypt the _ENCRYPTED blobs below)
    "ENCRYPTION_SECRET",
    "ENCRYPTION_SALT",

    # Database
    "DATABASE_SERVER",
    "DATABASE_NAME",
    "DATABASE_UID",
    "DATABASE_PWD",

    # Cloud database
    "CLOUD_DATABASE_SERVER",
    "CLOUD_DATABASE_NAME",
    "CLOUD_DATABASE_UID",
    "CLOUD_DATABASE_PWD",

    # Azure OpenAI
    "AZURE_OPENAI_BASE_URL",
    "AZURE_OPENAI_API_KEY_ENCRYPTED",
    "AZURE_OPENAI_BASE_URL_ALTERNATE",
    "AZURE_OPENAI_API_KEY_ALTERNATE_ENCRYPTED",
    "AZURE_OPENAI_BASE_URL_MINI",
    "AZURE_OPENAI_API_KEY_ENCRYPTED_MINI",

    # Other LLM providers
    "OPENAI_API_KEY_ENCRYPTED",
    "ANTHROPIC_API_KEY_ENCRYPTED",
    "TAVILY_API_KEY_ENCRYPTED",

    # Azure Communication Services
    "API_AZURE_COMM_CONN_STR",
    "API_AZURE_EMAIL_CONN_STR",
    "API_AZURE_EMAIL_SENDER",

    # Phone API
    "PHONE_BASE_URL",

    # Flask
    "FLASK_SECRET_KEY",
]


def main() -> int:
    env_path = _REPO_ROOT / ".env"
    output_path = _REPO_ROOT / "_build_config.py"

    if not env_path.exists():
        print(f"ERROR: .env not found at {env_path}", file=sys.stderr)
        return 1

    # dotenv_values returns exactly what's in the file, without merging os.environ
    env_values = dotenv_values(env_path)

    present: list[tuple[str, str]] = []
    missing: list[str] = []
    for key in ALLOWED_KEYS:
        val = env_values.get(key)
        if val is not None and val != "":
            present.append((key, val))
        else:
            missing.append(key)

    header = (
        "# ============================================================================\n"
        "# _build_config.py\n"
        "# Auto-generated by scripts/generate_build_config.py\n"
        "#\n"
        "# DO NOT COMMIT. DO NOT EDIT BY HAND.\n"
        "# Contains production credentials bundled into PyInstaller client builds.\n"
        "# Gitignored. Regenerated from .env before each build.\n"
        "# ============================================================================\n"
        "\n"
    )

    lines = [header]
    for key, val in present:
        # Use repr() so quotes, backslashes, newlines, etc. are safely escaped.
        lines.append(f"{key} = {val!r}\n")

    output_path.write_text("".join(lines), encoding="utf-8")

    print(f"Wrote {output_path.relative_to(_REPO_ROOT)}")
    print(f"  Included:  {len(present)} / {len(ALLOWED_KEYS)} allow-listed values")
    if missing:
        print(f"  Missing:   {len(missing)} (skipped — not in .env):")
        for k in missing:
            print(f"             - {k}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
